GET http://localhost:3000/api

###

GET http://localhost:3000/api/5ffe250fac48aacf116cd003

###

POST http://localhost:3000/api
Content-Type: application/json

{
    "name": "number four",
    "mailAddress": "2 development blvd",
    "jobAddress": "2 testing lane",
    "phoneNumber": "123-456-7890",
    "materialInstalled": "vinyl",
    "lastInstallDate": "2015-07-01"
}

### 
DELETE http://localhost:3000/api/john smith

###

PATCH http://localhost:3000/api/5ffe2e8404960fea7d7d07c3
Content-Type: application/json

{
    "name": "ohg yeah",
    "email": "schmorgen@borgen.com"
}